### PR TITLE
fix: remove duplicated slash if hideHostname option enabled

### LINKED ISSUE #1428: hide-hostname option adds a slash - openapi 3.0
Either a regression or a miss on the fix for #201. My guess is that this may be specific to openapi 3.0, as that's what I'm using and 3.0 wasn't yet supported when #201 was closed.

I'm seeing this using redoc-cli@0.9.12 (which [uses redoc 2.0.0-rc40](https://github.com/Redocly/redoc/commit/4e7c7228aadf56b4b73d2f68a3140c707fbf5bd7#diff-8f2f2c6de2bad1783500e34d29b4f24fb7a11ed1c482210edd80a9f47fe8e73aR1453)) with an openapi 3.0 spec with a single server.

Reproduction steps:
```
---
openapi: 3.0.0
info:
  title: Test API
  version: 0.0.1

servers:
  - url: https://api.example.com

paths:
  /some/example/path:
    get:
      responses:
        '204':
          description: No Content.
```

Then bundle it
```
$ redoc-cli --version
0.9.12

$ redoc-cli bundle openapi.yaml --options.hideHostname
$ open redoc-static.html
```

This is what you see when you click the dropdown:
Screen Shot 2020-10-22 at 8 21 33 PM

### PR DESCRIPTION
**Pull request by stasiukanya**
Fixes #1428

### CODE REVIEW

**Review by RomanHotsiy — APPROVED** [review]

File: src/components/Endpoint/Endpoint.tsx [hunk 1]
```diff
@@ -67,14 +67,15 @@ export class Endpoint extends React.Component<EndpointProps, EndpointState> {
                 const normalizedUrl = options.expandDefaultServerVariables
                   ? expandDefaultServerVariables(server.url, server.variables)
                   : server.url;
+                const basePath = getBasePath(normalizedUrl) === '/' ? '' : getBasePath(normalizedUrl);
```
Comment (RomanHotsiy) [inline src/components/Endpoint/Endpoint.tsx:70]:
```suggestion
                const basePath = getBasePath(normalizedUrl);
```

File: src/components/Endpoint/Endpoint.tsx [hunk 2]
```diff
@@ -67,14 +67,15 @@ export class Endpoint extends React.Component<EndpointProps, EndpointState> {
...
                 return (
                   <ServerItem key={normalizedUrl}>
                     <Markdown source={server.description || ''} compact={true} />
                     <SelectOnClick>
                       <ServerUrl>
                         <span>
                           {hideHostname || options.hideHostname
-                            ? getBasePath(normalizedUrl)
+                            ? basePath
```
Comment (RomanHotsiy) [inline src/components/Endpoint/Endpoint.tsx:78]:
```suggestion
                            ?  (basePath === '/' ? '' : basePath)
```

**Review by RomanHotsiy — CHANGES_REQUESTED** [review]

**Review by RomanHotsiy — APPROVED** [review]
